openapi: 3.0.0
info:
  title: MCSS API v13
  description: >-
    Documentation for the official MC Server Soft API.


    This for MCSS v13 and higher.  

    The API used in V12 can be found at
    [https://documenter.getpostman.com/view/7749159/TzJsexSC](https://documenter.getpostman.com/view/7749159/TzJsexSC)


    `Enabling SSL is recommended even when the certificate is self signed!`
  version: 1.0.0
servers:
  - url: https://localhost:25560
    description: Your local MCSS API server
components:
  securitySchemes:
    apikeyAuth:
      type: http
      scheme: apikey
  schemas:
    ServerDetails:
      type: object
      properties:
        guid:
          type: string
          example: e0ae4902-10ed-481f-aed0-fa1170ec779a
        status:
          type: int
          enum: [Offline, Online, Restarting, Starting, Stopping]
          example: 0
        name:
          type: string
          example: My Precious Server
        description:
          type: string
          example: Pvp & Minigames
        pathToFolder:
          type: string
          example: P:\path\to\mcss\servers\Purpur\
        folderName:
          type: string
          example: Purpur
        creationDate:
          type: date
          example: '2021-12-12T12:09:02.820296+01:00'
        isSetToAutoStart:
          type: bool
          example: false
        keepOnline:
          type: int
          enum: [None, Elevated, Aggressive]
          example: 0
        javaAllocatedMemory:
          type: int
          example: 1025
        javaStartupLine:
          type: string
          example: >-
            java -Xms1G -Xmx1G -XX:+UseG1GC -XX:+ParallelRefProcEnabled
            -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions
            -XX:+DisableExplicitGC -XX:+AlwaysPreTouch
            -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4
            -XX:G1MixedGCLiveThresholdPercent=90
            -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32
            -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1
            -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40
            -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20
            -XX:InitiatingHeapOccupancyPercent=15
            -Dusing.aikars.flags=https://mcflags.emc.gs
            -Daikars.new.flags=true -jar paper.jar nogui

security:
  - apikeyAuth: []
tags:
  - name: General
    description: General API calls that interact with mcss directly.
  - name: Servers
    description: API calls that involve multiple servers.
  - name: Server
    description: API calls that involve a single server.
  - name: Console
    description: API calls that involve the console from a single server.
  - name: Scheduler
    description: API calls that involve the scheduler from a single server.
paths:
  /api/v1:
    get:
      tags:
        - General
      summary: Get API version
      description: Get version info about mcss.
      responses:
        '200':
          description: OK
          content:
            application/json:
              example:
                isDevBuild: false
                mcssVersion: 13.0.0
                mcssApiVersion: 1.0.0
                uniqueIdentifier: 3664ac4e-23a5-4877-ab75-8412884acdb7
                youAreAwesome: true
        '401':
          description: Unauthorized
          content:
            text/plain:
              example: null
  /api/v1/servers:
    get:
      tags:
        - Servers
      summary: Get list of servers
      description: |-
        Return info of all servers.

        **filter (optional) : enum**  
        0 = None  
        1 = Minimal  
        2 = Status
      parameters:
        - name: filter
          in: query
          schema:
            type: string
          example: None
      responses:
        '200':
          description: OK
          content:
            application/json:
            
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ServerDetails'
        '401':
          description: Unauthorized
          content:
            text/plain:
              example: null
  /api/v1/servers/count:
    get:
      tags:
        - Servers
      summary: Get server count
      description: |-
        Get the total amount of servers.

        **filter (optional) : enum**  
        0 = None  
        1 = Online  
        2 = Offline  
        3 = ByServerType

        **serverTypeId (required when using ByServerType) : guid**  
        Guid of the server type.
      parameters:
        - name: filter
          in: query
          schema:
            type: string
          example: Online
        - name: serverTypeId
          in: query
          schema:
            type: string
          example: f738fb40-223e-4010-bd07-af4caabdf3dd
      responses:
        '200':
          description: OK
          content:
            application/json:
              example:
                count: 5
        '401':
          description: Unauthorized
          content:
            text/plain:
              example: null
  /api/v1/servers/:serverId:
    get:
      tags:
        - Server
      summary: Get server details
      description: |-
        Return info of a specific server.

        **filter (optional) : enum**  
        0 = None  
        1 = Minimal  
        2 = Status
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerDetails'
        '401':
          description: Unauthorized
          content:
            text/plain:
              example: null
        '404':
          description: Unknown Guid
          content:
            text/plain:
              example: null
  /api/v1/servers/:serverId/stats:
    get:
      tags:
        - Server
      summary: Get server stats
      description: Return stats of a specific server.
      responses:
        '200':
          description: OK
          content:
            application/json:
              example:
                latest:
                  cpu: 0
                  memoryUsed: 0
                  memoryLimit: 1025
                  playersOnline: 0
                  playerLimit: 21
                  startDate: 0
        '401':
          description: Unauthorized
          content:
            text/plain:
              example: null
        '404':
          description: Unknown Guid
          content:
            text/plain:
              example: null
  /api/v1/servers/:serverId/icon:
    get:
      tags:
        - Server
      summary: Get server icon
      description: Return the server-icon.png of a specific server.
      responses:
        '200':
          description: OK
          content:
            image/png:
              example: {}
        '401':
          description: Unauthorized
          content:
            text/plain:
              example: null
        '404':
          description: Unknown Guid
          content:
            text/plain:
              example: null
  /api/v1/servers/:serverId/execute/action:
    post:
      tags:
        - Server
      summary: Execute server action
      description: |-
        Change the status of a specific server.

        **action : enum**  
        0 = InvalidOrEmpty  
        1 = Stop  
        2 = Start  
        3 = Kill  
        4 = Restart
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                action: 1
      responses:
        '200':
          description: OK
          content:
            text/plain:
              example: null
        '401':
          description: Unauthorized
          content:
            text/plain:
              example: null
        '404':
          description: Unknown Guid
          content:
            text/plain:
              example: null
  /api/v1/servers/:serverId/execute/command:
    post:
      tags:
        - Server
      summary: Execute server command
      description: |-
        Run a server command on a specific server.

        **command (required) : string**  
        Server console command that should be executed.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                command: say My name’s not Kirk..It’s Skywalker. Luke Skywalker.
      responses:
        '200':
          description: OK
          content:
            text/plain:
              example: null
        '401':
          description: Unauthorized
          content:
            text/plain:
              example: null
        '404':
          description: Unknown Guid
          content:
            text/plain:
              example: null
  /api/v1/servers/:serverId/execute/commands:
    post:
      tags:
        - Server
      summary: Execute server commands
      description: |-
        Run multiple server commands on a specific server.

        **commands (required) : string\[\]**  
        List of server console commands that should be executed.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                commands:
                  - say Je suis mcss
                  - say Qui
                  - say C'est moi
      responses:
        '200':
          description: OK
          content:
            text/plain:
              example: null
        '401':
          description: Unauthorized
          content:
            text/plain:
              example: null
        '404':
          description: Unknown Guid
          content:
            text/plain:
              example: null
  /api/v1/servers/:serverId/console:
    get:
      tags:
        - Console
      summary: Get server console
      description: |-
        Return the console of a specific server.

        **amountOfLines (required) : integer**  
        Amount of lines you want to fetch, -1 to fetch everything.

        **takeFromBeginning (optional) : boolean**  
        Specify if you want to start fetching from the oldest lines first.

        **reversed (optional) : boolean**  
        Option to flip the line order.
      parameters:
        - name: AmountOfLines
          in: query
          schema:
            type: integer
          example: '5'
        - name: Reversed
          in: query
          schema:
            type: boolean
          example: 'true'
        - name: takeFromBeginning
          in: query
          schema:
            type: boolean
          example: 'true'
      responses:
        '200':
          description: OK
          content:
            application/json:
              example:
                - >-
                  [21:24:12] [Server thread/INFO]: [CraftBook] CraftBook 3.10.6
                  (1.18.1-1.18.2) is the latest version available, and the
                  updatability of it is: FAIL_NOVERSION. You currently have
                  version CraftBook 3.10.6 (1.18.1-1.18.2) installed.
                - >-
                  [21:24:12] [Thread-17/WARN]: [CraftBook] Please notify the
                  author of this error.
                - >-
                  [21:24:12] [Thread-17/WARN]: [CraftBook] File versions should
                  follow the format 'PluginName vVERSION'
                - >-
                  [21:24:12] [Thread-17/WARN]: [CraftBook] The author of this
                  plugin has misconfigured their Auto Update system
                - >-
                  [21:24:12] [Server thread/INFO]: [CraftBook] 1875 chunk(s) for
                  3 world(s) processed (109ms elapsed)
        '401':
          description: Unauthorized
          content:
            text/plain:
              example: null
        '404':
          description: Unknown Guid
          content:
            text/plain:
              example: null
  /api/v1/servers/:serverId/console/outdated:
    get:
      tags:
        - Console
      summary: Check if console is outdated
      description: >-
        Check if your version of the console is outdated. This by sending the
        last 2 last lines for comparison.


        **secondLastLine (required)**  

        Second last line you want to check.


        **lastLine (required)**  

        Last line you want to check.
      parameters:
        - name: secondLastLine
          in: query
          schema:
            type: string
          example: '[19:25:31] [Server thread/INFO]: Closing Thread Pool'
        - name: lastLine
          in: query
          schema:
            type: string
          example: '[19:25:31] [Server thread/INFO]: Closing Server'
      responses:
        '200':
          description: OK
          content:
            application/json:
              example:
                isOutdated: false
        '401':
          description: Unauthorized
          content:
            text/plain:
              example: null
        '404':
          description: Unknown Guid
          content:
            text/plain:
              example: null
  /api/v1/servers/:serverId/scheduler:
    get:
      tags:
        - Scheduler
      summary: Get scheduler details
      description: Return basic info about the scheduler of a specific server.
      responses:
        '200':
          description: OK
          content:
            application/json:
              example:
                tasks: 8
                interval: 4
                fixedTime: 3
                timeless: 1
        '401':
          description: Unauthorized
          content:
            text/plain:
              example: null
        '404':
          description: Unknown Guid
          content:
            text/plain:
              example: null
  /api/v1/servers/:serverId/scheduler/tasks:
    get:
      tags:
        - Scheduler
      summary: Get list of tasks
      description: |-
        Return all tasks from a specific server.

        **filter (optional) : enum**  
        0 = None  
        1 = FixedTime  
        2 = Interval  
        3 = Timeless
      parameters:
        - name: filter
          in: query
          example: None
      responses:
        '200':
          description: OK
          content:
            application/json:
              example:
                - taskId: a3e0fc6b-1965-4745-a527-090c83b22079
                  guidOfServer: e0ae4902-10ed-481f-aed0-fa1170ec779a
                  name: 1min restart announcement
                  enabled: false
                  timing:
                    timeSpan: '18:59:00'
                    repeat: true
                  job:
                    commands:
                      - say Restarting in 1min.
                - taskId: 8fcab652-cb96-4c57-b12b-f1d0db694a2b
                  guidOfServer: e0ae4902-10ed-481f-aed0-fa1170ec779a
                  name: Timeless
                  enabled: true
                  timing: {}
                  job:
                    action: 1
        '401':
          description: Unauthorized
          content:
            text/plain:
              example: null
        '404':
          description: Unknown Guid
          content:
            text/plain:
              example: null
    post:
      tags:
        - Scheduler
      summary: Create task
      description: |-
        Create a new task.

        **task (required)**  
        \- name (required) : string  
        \- enabled (optional) : boolean  
        \- timing (required) : object  
        \- job (required): object

        ### **Types of Timings (3)**

        **fixedTime**  
        \- repeat: boolean  
        \- timeSpan: TimeSpan

        **interval**  
        \- repeat: boolean  
        \- interval: integer

        **timeless**  
        // no parameters

        ### **Types of Jobs (3)**

        **ServerAction**  
        \- action : ServerAction  
        // 0 or Stop  
        // 1 or Start  
        // 2 or Kill  
        // 3 or Restart

        **RunCommands**  
        \- commands: string\[\]

        **StartBackup**  
        \- backupIdentifier: guid
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: Made with the api s
                enabled: true
                timing:
                  repeat: true
                  interval: 150
                job:
                  commands:
                    - /say hello from the api
      responses:
        '201':
          description: Created
          content:
            text/plain:
              example: null
        '400':
          description: Invalid Task Details
          content:
            text/plain:
              example: null
        '401':
          description: Unauthorized
          content:
            text/plain:
              example: null
        '404':
          description: Unknown Guid
          content:
            text/plain:
              example: null
  /api/v1/servers/:serverId/scheduler/tasks/:taskId:
    get:
      tags:
        - Scheduler
      summary: Get task
      description: Return a specific task from a specific server.
      responses:
        '200':
          description: OK
          content:
            application/json:
              example:
                taskId: 4a582b48-5f37-4586-88f9-a37af96db08a
                guidOfServer: e0ae4902-10ed-481f-aed0-fa1170ec779a
                name: Made with the api2
                enabled: false
                timing:
                  repeat: false
                  interval: 151
                job:
                  commands:
                    - /say hello from the api2
                    - /say hello from the api3
        '401':
          description: Unauthorized
          content:
            text/plain:
              example: null
        '404':
          description: Unknown Guid
          content:
            text/plain:
              example: null
    put:
      tags:
        - Scheduler
      summary: Edit task
      description: >-
        Update a specific server task.  

        You can not change the timing or job of the original task, only its
        values.


        **task (required)**  

        *Detailed parameter declaration can be found in the* ***Create Task***
        *route.*
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: Made with the api2
                enabled: false
                timing:
                  repeat: false
                  interval: 151
                job:
                  commands:
                    - /say hello from the api2
                    - /say hello from the api3
      responses:
        '200':
          description: OK
          content:
            text/plain:
              example: null
        '401':
          description: Unauthorized
          content:
            text/plain:
              example: null
        '404':
          description: Unknown Guid/Task
          content:
            text/plain:
              example: null
        '409':
          description: Timming type can not be changed.
          content:
            text/plain:
              example: null
    delete:
      tags:
        - Scheduler
      summary: Delete task
      description: Delete a specific server task.
      responses:
        '200':
          description: Deleted
          content:
            text/plain:
              example: null
        '401':
          description: Unauthorized
          content:
            text/plain:
              example: null
        '404':
          description: Unknown Task
          content:
            text/plain:
              example: null
    post:
      tags:
        - Scheduler
      summary: Run task
      description: Run a specific server task.
      requestBody:
        content: {}
      responses:
        '200':
          description: OK
          content:
            text/plain:
              example: null
        '401':
          description: Unauthorized
          content:
            text/plain:
              example: null
        '404':
          description: Unknown Guid/Task
          content:
            text/plain:
              example: null
